DASH_VERSION=0.5.10

.PHONY: all
all: dash

.PHONY: dash
dash:

# configure --host=i386-shk --enable-static --prefix=??? --sysroot???
# make CC=i386-shk-gcc
# make install-exec # to avoid installing man page
