#include <stdbool.h>
#include <kernel/idt.h>

extern void isr_stub_0(void);
extern void isr_stub_1(void);
extern void isr_stub_2(void);
extern void isr_stub_3(void);
extern void isr_stub_4(void);
extern void isr_stub_5(void);
extern void isr_stub_6(void);
extern void isr_stub_7(void);
extern void isr_stub_8(void);
extern void isr_stub_9(void);
extern void isr_stub_10(void);
extern void isr_stub_11(void);
extern void isr_stub_12(void);
extern void isr_stub_13(void);
extern void isr_stub_14(void);
extern void isr_stub_15(void);
extern void isr_stub_16(void);
extern void isr_stub_17(void);
extern void isr_stub_18(void);
extern void isr_stub_19(void);
extern void isr_stub_20(void);
extern void isr_stub_21(void);
extern void isr_stub_22(void);
extern void isr_stub_23(void);
extern void isr_stub_24(void);
extern void isr_stub_25(void);
extern void isr_stub_26(void);
extern void isr_stub_27(void);
extern void isr_stub_28(void);
extern void isr_stub_29(void);
extern void isr_stub_30(void);
extern void isr_stub_31(void);
extern void isr_stub_32(void);
extern void isr_stub_33(void);
extern void isr_stub_34(void);
extern void isr_stub_35(void);
extern void isr_stub_36(void);
extern void isr_stub_37(void);
extern void isr_stub_38(void);
extern void isr_stub_39(void);
extern void isr_stub_40(void);
extern void isr_stub_41(void);
extern void isr_stub_42(void);
extern void isr_stub_43(void);
extern void isr_stub_44(void);
extern void isr_stub_45(void);
extern void isr_stub_46(void);
extern void isr_stub_47(void);
extern void isr_stub_48(void);
extern void isr_stub_49(void);
extern void isr_stub_50(void);
extern void isr_stub_51(void);
extern void isr_stub_52(void);
extern void isr_stub_53(void);
extern void isr_stub_54(void);
extern void isr_stub_55(void);
extern void isr_stub_56(void);
extern void isr_stub_57(void);
extern void isr_stub_58(void);
extern void isr_stub_59(void);
extern void isr_stub_60(void);
extern void isr_stub_61(void);
extern void isr_stub_62(void);
extern void isr_stub_63(void);
extern void isr_stub_64(void);
extern void isr_stub_65(void);
extern void isr_stub_66(void);
extern void isr_stub_67(void);
extern void isr_stub_68(void);
extern void isr_stub_69(void);
extern void isr_stub_70(void);
extern void isr_stub_71(void);
extern void isr_stub_72(void);
extern void isr_stub_73(void);
extern void isr_stub_74(void);
extern void isr_stub_75(void);
extern void isr_stub_76(void);
extern void isr_stub_77(void);
extern void isr_stub_78(void);
extern void isr_stub_79(void);
extern void isr_stub_80(void);
extern void isr_stub_81(void);
extern void isr_stub_82(void);
extern void isr_stub_83(void);
extern void isr_stub_84(void);
extern void isr_stub_85(void);
extern void isr_stub_86(void);
extern void isr_stub_87(void);
extern void isr_stub_88(void);
extern void isr_stub_89(void);
extern void isr_stub_90(void);
extern void isr_stub_91(void);
extern void isr_stub_92(void);
extern void isr_stub_93(void);
extern void isr_stub_94(void);
extern void isr_stub_95(void);
extern void isr_stub_96(void);
extern void isr_stub_97(void);
extern void isr_stub_98(void);
extern void isr_stub_99(void);
extern void isr_stub_100(void);
extern void isr_stub_101(void);
extern void isr_stub_102(void);
extern void isr_stub_103(void);
extern void isr_stub_104(void);
extern void isr_stub_105(void);
extern void isr_stub_106(void);
extern void isr_stub_107(void);
extern void isr_stub_108(void);
extern void isr_stub_109(void);
extern void isr_stub_110(void);
extern void isr_stub_111(void);
extern void isr_stub_112(void);
extern void isr_stub_113(void);
extern void isr_stub_114(void);
extern void isr_stub_115(void);
extern void isr_stub_116(void);
extern void isr_stub_117(void);
extern void isr_stub_118(void);
extern void isr_stub_119(void);
extern void isr_stub_120(void);
extern void isr_stub_121(void);
extern void isr_stub_122(void);
extern void isr_stub_123(void);
extern void isr_stub_124(void);
extern void isr_stub_125(void);
extern void isr_stub_126(void);
extern void isr_stub_127(void);
extern void isr_stub_128(void);
extern void isr_stub_129(void);
extern void isr_stub_130(void);
extern void isr_stub_131(void);
extern void isr_stub_132(void);
extern void isr_stub_133(void);
extern void isr_stub_134(void);
extern void isr_stub_135(void);
extern void isr_stub_136(void);
extern void isr_stub_137(void);
extern void isr_stub_138(void);
extern void isr_stub_139(void);
extern void isr_stub_140(void);
extern void isr_stub_141(void);
extern void isr_stub_142(void);
extern void isr_stub_143(void);
extern void isr_stub_144(void);
extern void isr_stub_145(void);
extern void isr_stub_146(void);
extern void isr_stub_147(void);
extern void isr_stub_148(void);
extern void isr_stub_149(void);
extern void isr_stub_150(void);
extern void isr_stub_151(void);
extern void isr_stub_152(void);
extern void isr_stub_153(void);
extern void isr_stub_154(void);
extern void isr_stub_155(void);
extern void isr_stub_156(void);
extern void isr_stub_157(void);
extern void isr_stub_158(void);
extern void isr_stub_159(void);
extern void isr_stub_160(void);
extern void isr_stub_161(void);
extern void isr_stub_162(void);
extern void isr_stub_163(void);
extern void isr_stub_164(void);
extern void isr_stub_165(void);
extern void isr_stub_166(void);
extern void isr_stub_167(void);
extern void isr_stub_168(void);
extern void isr_stub_169(void);
extern void isr_stub_170(void);
extern void isr_stub_171(void);
extern void isr_stub_172(void);
extern void isr_stub_173(void);
extern void isr_stub_174(void);
extern void isr_stub_175(void);
extern void isr_stub_176(void);
extern void isr_stub_177(void);
extern void isr_stub_178(void);
extern void isr_stub_179(void);
extern void isr_stub_180(void);
extern void isr_stub_181(void);
extern void isr_stub_182(void);
extern void isr_stub_183(void);
extern void isr_stub_184(void);
extern void isr_stub_185(void);
extern void isr_stub_186(void);
extern void isr_stub_187(void);
extern void isr_stub_188(void);
extern void isr_stub_189(void);
extern void isr_stub_190(void);
extern void isr_stub_191(void);
extern void isr_stub_192(void);
extern void isr_stub_193(void);
extern void isr_stub_194(void);
extern void isr_stub_195(void);
extern void isr_stub_196(void);
extern void isr_stub_197(void);
extern void isr_stub_198(void);
extern void isr_stub_199(void);
extern void isr_stub_200(void);
extern void isr_stub_201(void);
extern void isr_stub_202(void);
extern void isr_stub_203(void);
extern void isr_stub_204(void);
extern void isr_stub_205(void);
extern void isr_stub_206(void);
extern void isr_stub_207(void);
extern void isr_stub_208(void);
extern void isr_stub_209(void);
extern void isr_stub_210(void);
extern void isr_stub_211(void);
extern void isr_stub_212(void);
extern void isr_stub_213(void);
extern void isr_stub_214(void);
extern void isr_stub_215(void);
extern void isr_stub_216(void);
extern void isr_stub_217(void);
extern void isr_stub_218(void);
extern void isr_stub_219(void);
extern void isr_stub_220(void);
extern void isr_stub_221(void);
extern void isr_stub_222(void);
extern void isr_stub_223(void);
extern void isr_stub_224(void);
extern void isr_stub_225(void);
extern void isr_stub_226(void);
extern void isr_stub_227(void);
extern void isr_stub_228(void);
extern void isr_stub_229(void);
extern void isr_stub_230(void);
extern void isr_stub_231(void);
extern void isr_stub_232(void);
extern void isr_stub_233(void);
extern void isr_stub_234(void);
extern void isr_stub_235(void);
extern void isr_stub_236(void);
extern void isr_stub_237(void);
extern void isr_stub_238(void);
extern void isr_stub_239(void);
extern void isr_stub_240(void);
extern void isr_stub_241(void);
extern void isr_stub_242(void);
extern void isr_stub_243(void);
extern void isr_stub_244(void);
extern void isr_stub_245(void);
extern void isr_stub_246(void);
extern void isr_stub_247(void);
extern void isr_stub_248(void);
extern void isr_stub_249(void);
extern void isr_stub_250(void);
extern void isr_stub_251(void);
extern void isr_stub_252(void);
extern void isr_stub_253(void);
extern void isr_stub_254(void);
extern void isr_stub_255(void);

inline void set_entry(volatile struct IDTEntry *entry, void (*handler)(void), bool restricted) {
	uint32_t base_address = (uint32_t)handler;
	entry->base_address_low = base_address & 0xFFFF;
	entry->base_address_high = (base_address >> 16) & 0xFFFF;
	entry->selector = 0x8;
	entry->reserved = 0;
	entry->type = 0xE; /* 80386 32-bit interrupt gate */
	entry->storage_segment = 0; /* 0 for interrupt gates */
	entry->privilege = restricted ? 0 : 3;
	entry->present = 1;
}

void idt_init(volatile struct IDT *idt) {
	idt->descriptor.limiter = sizeof(idt->entries);
	idt->descriptor.base_address = &idt->entries;

	set_entry(&idt->entries[  0], isr_stub_0,   true);
	set_entry(&idt->entries[  1], isr_stub_1,   true);
	set_entry(&idt->entries[  2], isr_stub_2,   true);
	set_entry(&idt->entries[  3], isr_stub_3,   true);
	set_entry(&idt->entries[  4], isr_stub_4,   true);
	set_entry(&idt->entries[  5], isr_stub_5,   true);
	set_entry(&idt->entries[  6], isr_stub_6,   true);
	set_entry(&idt->entries[  7], isr_stub_7,   true);
	set_entry(&idt->entries[  8], isr_stub_8,   true);
	set_entry(&idt->entries[  9], isr_stub_9,   true);
	set_entry(&idt->entries[ 10], isr_stub_10,  true);
	set_entry(&idt->entries[ 11], isr_stub_11,  true);
	set_entry(&idt->entries[ 12], isr_stub_12,  true);
	set_entry(&idt->entries[ 13], isr_stub_13,  true);
	set_entry(&idt->entries[ 14], isr_stub_14,  true);
	set_entry(&idt->entries[ 15], isr_stub_15,  true);
	set_entry(&idt->entries[ 16], isr_stub_16,  true);
	set_entry(&idt->entries[ 17], isr_stub_17,  true);
	set_entry(&idt->entries[ 18], isr_stub_18,  true);
	set_entry(&idt->entries[ 19], isr_stub_19,  true);
	set_entry(&idt->entries[ 20], isr_stub_20,  true);
	set_entry(&idt->entries[ 21], isr_stub_21,  true);
	set_entry(&idt->entries[ 22], isr_stub_22,  true);
	set_entry(&idt->entries[ 23], isr_stub_23,  true);
	set_entry(&idt->entries[ 24], isr_stub_24,  true);
	set_entry(&idt->entries[ 25], isr_stub_25,  true);
	set_entry(&idt->entries[ 26], isr_stub_26,  true);
	set_entry(&idt->entries[ 27], isr_stub_27,  true);
	set_entry(&idt->entries[ 28], isr_stub_28,  true);
	set_entry(&idt->entries[ 29], isr_stub_29,  true);
	set_entry(&idt->entries[ 30], isr_stub_30,  true);
	set_entry(&idt->entries[ 31], isr_stub_31,  true);
	set_entry(&idt->entries[ 32], isr_stub_32,  true);
	set_entry(&idt->entries[ 33], isr_stub_33,  true);
	set_entry(&idt->entries[ 34], isr_stub_34,  true);
	set_entry(&idt->entries[ 35], isr_stub_35,  true);
	set_entry(&idt->entries[ 36], isr_stub_36,  true);
	set_entry(&idt->entries[ 37], isr_stub_37,  true);
	set_entry(&idt->entries[ 38], isr_stub_38,  true);
	set_entry(&idt->entries[ 39], isr_stub_39,  true);
	set_entry(&idt->entries[ 40], isr_stub_40,  true);
	set_entry(&idt->entries[ 41], isr_stub_41,  true);
	set_entry(&idt->entries[ 42], isr_stub_42,  true);
	set_entry(&idt->entries[ 43], isr_stub_43,  true);
	set_entry(&idt->entries[ 44], isr_stub_44,  true);
	set_entry(&idt->entries[ 45], isr_stub_45,  true);
	set_entry(&idt->entries[ 46], isr_stub_46,  true);
	set_entry(&idt->entries[ 47], isr_stub_47,  true);
	set_entry(&idt->entries[ 48], isr_stub_48,  true);
	set_entry(&idt->entries[ 49], isr_stub_49,  true);
	set_entry(&idt->entries[ 50], isr_stub_50,  true);
	set_entry(&idt->entries[ 51], isr_stub_51,  true);
	set_entry(&idt->entries[ 52], isr_stub_52,  true);
	set_entry(&idt->entries[ 53], isr_stub_53,  true);
	set_entry(&idt->entries[ 54], isr_stub_54,  true);
	set_entry(&idt->entries[ 55], isr_stub_55,  true);
	set_entry(&idt->entries[ 56], isr_stub_56,  true);
	set_entry(&idt->entries[ 57], isr_stub_57,  true);
	set_entry(&idt->entries[ 58], isr_stub_58,  true);
	set_entry(&idt->entries[ 59], isr_stub_59,  true);
	set_entry(&idt->entries[ 60], isr_stub_60,  true);
	set_entry(&idt->entries[ 61], isr_stub_61,  true);
	set_entry(&idt->entries[ 62], isr_stub_62,  true);
	set_entry(&idt->entries[ 63], isr_stub_63,  true);
	set_entry(&idt->entries[ 64], isr_stub_64,  true);
	set_entry(&idt->entries[ 65], isr_stub_65,  true);
	set_entry(&idt->entries[ 66], isr_stub_66,  true);
	set_entry(&idt->entries[ 67], isr_stub_67,  true);
	set_entry(&idt->entries[ 68], isr_stub_68,  true);
	set_entry(&idt->entries[ 69], isr_stub_69,  true);
	set_entry(&idt->entries[ 70], isr_stub_70,  true);
	set_entry(&idt->entries[ 71], isr_stub_71,  true);
	set_entry(&idt->entries[ 72], isr_stub_72,  true);
	set_entry(&idt->entries[ 73], isr_stub_73,  true);
	set_entry(&idt->entries[ 74], isr_stub_74,  true);
	set_entry(&idt->entries[ 75], isr_stub_75,  true);
	set_entry(&idt->entries[ 76], isr_stub_76,  true);
	set_entry(&idt->entries[ 77], isr_stub_77,  true);
	set_entry(&idt->entries[ 78], isr_stub_78,  true);
	set_entry(&idt->entries[ 79], isr_stub_79,  true);
	set_entry(&idt->entries[ 80], isr_stub_80,  true);
	set_entry(&idt->entries[ 81], isr_stub_81,  true);
	set_entry(&idt->entries[ 82], isr_stub_82,  true);
	set_entry(&idt->entries[ 83], isr_stub_83,  true);
	set_entry(&idt->entries[ 84], isr_stub_84,  true);
	set_entry(&idt->entries[ 85], isr_stub_85,  true);
	set_entry(&idt->entries[ 86], isr_stub_86,  true);
	set_entry(&idt->entries[ 87], isr_stub_87,  true);
	set_entry(&idt->entries[ 88], isr_stub_88,  true);
	set_entry(&idt->entries[ 89], isr_stub_89,  true);
	set_entry(&idt->entries[ 90], isr_stub_90,  true);
	set_entry(&idt->entries[ 91], isr_stub_91,  true);
	set_entry(&idt->entries[ 92], isr_stub_92,  true);
	set_entry(&idt->entries[ 93], isr_stub_93,  true);
	set_entry(&idt->entries[ 94], isr_stub_94,  true);
	set_entry(&idt->entries[ 95], isr_stub_95,  true);
	set_entry(&idt->entries[ 96], isr_stub_96,  true);
	set_entry(&idt->entries[ 97], isr_stub_97,  true);
	set_entry(&idt->entries[ 98], isr_stub_98,  true);
	set_entry(&idt->entries[ 99], isr_stub_99,  true);
	set_entry(&idt->entries[100], isr_stub_100, true);
	set_entry(&idt->entries[101], isr_stub_101, true);
	set_entry(&idt->entries[102], isr_stub_102, true);
	set_entry(&idt->entries[103], isr_stub_103, true);
	set_entry(&idt->entries[104], isr_stub_104, true);
	set_entry(&idt->entries[105], isr_stub_105, true);
	set_entry(&idt->entries[106], isr_stub_106, true);
	set_entry(&idt->entries[107], isr_stub_107, true);
	set_entry(&idt->entries[108], isr_stub_108, true);
	set_entry(&idt->entries[109], isr_stub_109, true);
	set_entry(&idt->entries[110], isr_stub_110, true);
	set_entry(&idt->entries[111], isr_stub_111, true);
	set_entry(&idt->entries[112], isr_stub_112, true);
	set_entry(&idt->entries[113], isr_stub_113, true);
	set_entry(&idt->entries[114], isr_stub_114, true);
	set_entry(&idt->entries[115], isr_stub_115, true);
	set_entry(&idt->entries[116], isr_stub_116, true);
	set_entry(&idt->entries[117], isr_stub_117, true);
	set_entry(&idt->entries[118], isr_stub_118, true);
	set_entry(&idt->entries[119], isr_stub_119, true);
	set_entry(&idt->entries[120], isr_stub_120, true);
	set_entry(&idt->entries[121], isr_stub_121, true);
	set_entry(&idt->entries[122], isr_stub_122, true);
	set_entry(&idt->entries[123], isr_stub_123, true);
	set_entry(&idt->entries[124], isr_stub_124, true);
	set_entry(&idt->entries[125], isr_stub_125, true);
	set_entry(&idt->entries[126], isr_stub_126, true);
	set_entry(&idt->entries[127], isr_stub_127, true);
	set_entry(&idt->entries[128], isr_stub_128, false); /* syscall interface (128 == 0x80) */
	set_entry(&idt->entries[129], isr_stub_129, true);
	set_entry(&idt->entries[130], isr_stub_130, true);
	set_entry(&idt->entries[131], isr_stub_131, true);
	set_entry(&idt->entries[132], isr_stub_132, true);
	set_entry(&idt->entries[133], isr_stub_133, true);
	set_entry(&idt->entries[134], isr_stub_134, true);
	set_entry(&idt->entries[135], isr_stub_135, true);
	set_entry(&idt->entries[136], isr_stub_136, true);
	set_entry(&idt->entries[137], isr_stub_137, true);
	set_entry(&idt->entries[138], isr_stub_138, true);
	set_entry(&idt->entries[139], isr_stub_139, true);
	set_entry(&idt->entries[140], isr_stub_140, true);
	set_entry(&idt->entries[141], isr_stub_141, true);
	set_entry(&idt->entries[142], isr_stub_142, true);
	set_entry(&idt->entries[143], isr_stub_143, true);
	set_entry(&idt->entries[144], isr_stub_144, true);
	set_entry(&idt->entries[145], isr_stub_145, true);
	set_entry(&idt->entries[146], isr_stub_146, true);
	set_entry(&idt->entries[147], isr_stub_147, true);
	set_entry(&idt->entries[148], isr_stub_148, true);
	set_entry(&idt->entries[149], isr_stub_149, true);
	set_entry(&idt->entries[150], isr_stub_150, true);
	set_entry(&idt->entries[151], isr_stub_151, true);
	set_entry(&idt->entries[152], isr_stub_152, true);
	set_entry(&idt->entries[153], isr_stub_153, true);
	set_entry(&idt->entries[154], isr_stub_154, true);
	set_entry(&idt->entries[155], isr_stub_155, true);
	set_entry(&idt->entries[156], isr_stub_156, true);
	set_entry(&idt->entries[157], isr_stub_157, true);
	set_entry(&idt->entries[158], isr_stub_158, true);
	set_entry(&idt->entries[159], isr_stub_159, true);
	set_entry(&idt->entries[160], isr_stub_160, true);
	set_entry(&idt->entries[161], isr_stub_161, true);
	set_entry(&idt->entries[162], isr_stub_162, true);
	set_entry(&idt->entries[163], isr_stub_163, true);
	set_entry(&idt->entries[164], isr_stub_164, true);
	set_entry(&idt->entries[165], isr_stub_165, true);
	set_entry(&idt->entries[166], isr_stub_166, true);
	set_entry(&idt->entries[167], isr_stub_167, true);
	set_entry(&idt->entries[168], isr_stub_168, true);
	set_entry(&idt->entries[169], isr_stub_169, true);
	set_entry(&idt->entries[170], isr_stub_170, true);
	set_entry(&idt->entries[171], isr_stub_171, true);
	set_entry(&idt->entries[172], isr_stub_172, true);
	set_entry(&idt->entries[173], isr_stub_173, true);
	set_entry(&idt->entries[174], isr_stub_174, true);
	set_entry(&idt->entries[175], isr_stub_175, true);
	set_entry(&idt->entries[176], isr_stub_176, true);
	set_entry(&idt->entries[177], isr_stub_177, true);
	set_entry(&idt->entries[178], isr_stub_178, true);
	set_entry(&idt->entries[179], isr_stub_179, true);
	set_entry(&idt->entries[180], isr_stub_180, true);
	set_entry(&idt->entries[181], isr_stub_181, true);
	set_entry(&idt->entries[182], isr_stub_182, true);
	set_entry(&idt->entries[183], isr_stub_183, true);
	set_entry(&idt->entries[184], isr_stub_184, true);
	set_entry(&idt->entries[185], isr_stub_185, true);
	set_entry(&idt->entries[186], isr_stub_186, true);
	set_entry(&idt->entries[187], isr_stub_187, true);
	set_entry(&idt->entries[188], isr_stub_188, true);
	set_entry(&idt->entries[189], isr_stub_189, true);
	set_entry(&idt->entries[190], isr_stub_190, true);
	set_entry(&idt->entries[191], isr_stub_191, true);
	set_entry(&idt->entries[192], isr_stub_192, true);
	set_entry(&idt->entries[193], isr_stub_193, true);
	set_entry(&idt->entries[194], isr_stub_194, true);
	set_entry(&idt->entries[195], isr_stub_195, true);
	set_entry(&idt->entries[196], isr_stub_196, true);
	set_entry(&idt->entries[197], isr_stub_197, true);
	set_entry(&idt->entries[198], isr_stub_198, true);
	set_entry(&idt->entries[199], isr_stub_199, true);
	set_entry(&idt->entries[200], isr_stub_200, true);
	set_entry(&idt->entries[201], isr_stub_201, true);
	set_entry(&idt->entries[202], isr_stub_202, true);
	set_entry(&idt->entries[203], isr_stub_203, true);
	set_entry(&idt->entries[204], isr_stub_204, true);
	set_entry(&idt->entries[205], isr_stub_205, true);
	set_entry(&idt->entries[206], isr_stub_206, true);
	set_entry(&idt->entries[207], isr_stub_207, true);
	set_entry(&idt->entries[208], isr_stub_208, true);
	set_entry(&idt->entries[209], isr_stub_209, true);
	set_entry(&idt->entries[210], isr_stub_210, true);
	set_entry(&idt->entries[211], isr_stub_211, true);
	set_entry(&idt->entries[212], isr_stub_212, true);
	set_entry(&idt->entries[213], isr_stub_213, true);
	set_entry(&idt->entries[214], isr_stub_214, true);
	set_entry(&idt->entries[215], isr_stub_215, true);
	set_entry(&idt->entries[216], isr_stub_216, true);
	set_entry(&idt->entries[217], isr_stub_217, true);
	set_entry(&idt->entries[218], isr_stub_218, true);
	set_entry(&idt->entries[219], isr_stub_219, true);
	set_entry(&idt->entries[220], isr_stub_220, true);
	set_entry(&idt->entries[221], isr_stub_221, true);
	set_entry(&idt->entries[222], isr_stub_222, true);
	set_entry(&idt->entries[223], isr_stub_223, true);
	set_entry(&idt->entries[224], isr_stub_224, true);
	set_entry(&idt->entries[225], isr_stub_225, true);
	set_entry(&idt->entries[226], isr_stub_226, true);
	set_entry(&idt->entries[227], isr_stub_227, true);
	set_entry(&idt->entries[228], isr_stub_228, true);
	set_entry(&idt->entries[229], isr_stub_229, true);
	set_entry(&idt->entries[230], isr_stub_230, true);
	set_entry(&idt->entries[231], isr_stub_231, true);
	set_entry(&idt->entries[232], isr_stub_232, true);
	set_entry(&idt->entries[233], isr_stub_233, true);
	set_entry(&idt->entries[234], isr_stub_234, true);
	set_entry(&idt->entries[235], isr_stub_235, true);
	set_entry(&idt->entries[236], isr_stub_236, true);
	set_entry(&idt->entries[237], isr_stub_237, true);
	set_entry(&idt->entries[238], isr_stub_238, true);
	set_entry(&idt->entries[239], isr_stub_239, true);
	set_entry(&idt->entries[240], isr_stub_240, true);
	set_entry(&idt->entries[241], isr_stub_241, true);
	set_entry(&idt->entries[242], isr_stub_242, true);
	set_entry(&idt->entries[243], isr_stub_243, true);
	set_entry(&idt->entries[244], isr_stub_244, true);
	set_entry(&idt->entries[245], isr_stub_245, true);
	set_entry(&idt->entries[246], isr_stub_246, true);
	set_entry(&idt->entries[247], isr_stub_247, true);
	set_entry(&idt->entries[248], isr_stub_248, true);
	set_entry(&idt->entries[249], isr_stub_249, true);
	set_entry(&idt->entries[250], isr_stub_250, true);
	set_entry(&idt->entries[251], isr_stub_251, true);
	set_entry(&idt->entries[252], isr_stub_252, true);
	set_entry(&idt->entries[253], isr_stub_253, true);
	set_entry(&idt->entries[254], isr_stub_254, true);
	set_entry(&idt->entries[255], isr_stub_255, true);

	__asm__ __volatile__ ("lidt (%0)" : : "r" (&idt->descriptor));
}
